---
- name: Defer multiple CVEs for a specified number of days in Red Hat Advanced Cluster Security for Kubernetes (RHACS)
  hosts: localhost
  gather_facts: true

  vars_files:
    - vault

  vars:
    acs_host: "{{ vaulted_acs_host }}"
    acs_token: "{{ vaulted_acs_token }}"
    cves_enriched: "{{ cves.split('\n') | cve2rhsa }}"

  tasks:
    - name: "Defer the CVEs"
      ansible.builtin.uri:
        url: https://{{ acs_host }}/v1/cve/requests/defer
        headers:
          Authorization: "Bearer {{ acs_token }}"
        method: POST
        body: |
          {
            "cve": "{{ item }}",
            "scope": {"globalScope": {}},
            "comment": "{{ comment }}",
            "expiresWhenFixed": true,
            "expiresOn": "{{ lookup('pipe', 'date +%Y-%m-%dT%H:%M:%SZ -d \"+{{ days } days\"') }}"
          }
        force_basic_auth: true
        status_code: 200
        body_format: json
        validate_certs: false
      loop: "{{ cves_enriched }}"
      no_log: false
      changed_when: true
