---
- name: Defer a CVE for a specified number of  days in Red Hat Advanced Cluster Security for Kubernetes
  hosts: localhost
  gather_facts: true

  vars_files:
  - vault

  vars:
    acs_host: "{{ vaulted_acs_host }}"
    acs_token: "{{ vaulted_acs_token }}"

  tasks:
    - name: Defer the CVE
      uri:
        url: https://{{ acs_host }}/v1/cve/requests/defer
        headers:
          Authorization: "Bearer {{ acs_token }}"
        method: POST
        body: {"cve": "{{ cve }}", "scope": {"globalScope": {}},"comment": "Deferred {{ cve }}","expiresWhenFixed": true, "expiresOn": "{{ lookup('pipe', 'date +%Y-%m-%dT%H:%M:%SZ -d \"+{{ days }} days\"') }}" }
        force_basic_auth: yes
        status_code: 200
        body_format: json
        validate_certs: false
      no_log: false
      changed_when: true
