---
- name: Flag a CVE as a false positive Red Hat Advanced Cluster Security for Kubernetes
  hosts: localhost
  gather_facts: true

  vars_files:
    - vault

  vars:
    acs_host: "{{ vaulted_acs_host }}"
    acs_token: "{{ vaulted_acs_token }}"

  tasks:
    - name: Mark the CVEs as false-positive
      ansible.builtin.uri:
        url: https://{{ acs_host }}/v1/cve/requests/false-positive
        headers:
          Authorization: "Bearer {{ acs_token }}"
        method: POST
        body: |
          {
            "cve": "{{ cve }}",
            "scope": {"globalScope": {}},
            "comment": "Marked false-positive {{ cve }}"
          }
        force_basic_auth: true
        status_code: 200
        body_format: json
        validate_certs: false
      no_log: false
      changed_when: true
